let x = 10;

try {
  x = 10 / 0;
} catch (error) {
  console.log(error);
}